name: Deploy solvespace to PAAS env

on:
  workflow_dispatch: 
    inputs:
      environment: 
        description: 'Target environment (e.g., production, staging)'
        required: false
        default: 'pass'
        type: choice
        options:
          - test1
          - test2
          - test3


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0 

      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

    - name: Deploy files with rsync
      run: |
        ssh-keyscan -H ${{ secrets.PAAS_ENV_SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

        
        rsync -avz --delete \
          ./test/         \
          orth_github_user@${{ secrets.PAAS_ENV_SERVER_IP }}:/var/www/html/solvespace/ 
