name: Deploy solvespace to PAAS env

on:
  workflow_dispatch:  # 启用手动触发
    inputs:
      environment:  # 定义可选输入参数
        description: 'Target environment (e.g., production, staging)'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 检出你的仓库代码

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0  # 使用一个 Action 来设置 SSH Agent，方便使用密钥

      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # 使用之前创建的 Secret

    - name: Deploy files with rsync
      run: |
        ssh-keyscan -H ${{ secrets.PAAS_ENV_SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

        # 使用 rsync 同步文件。  修改这些内容以适应你的实际需求
        rsync -avz --delete \
          ./test/         \  # 本地要上传的内容的路径
          orth_github_user@${{ secrets.PAAS_ENV_SERVER_IP }}:/var/www/html/solvespace/  # 目标服务器的路径
