name: release wasm web

on:
  workflow_dispatch: # Always show "Run workflow" button, can not lazy trigger single job

jobs:
  build_release_web:
    name: Build Release Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: .github/scripts/install-web.sh
    - uses: mymindstorm/setup-emsdk@v14
    - name: Verify emssdk
      run: emcc -v
    - name: Build & Pack
      run: |
        .github/scripts/build-web.sh release
        cd build/bin
        rm *.a || true
        cd ../../
        mv build/bin geometry
        zip -r geometry.zip geometry
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_SSH_PAAS_IP }} >> ~/.ssh/known_hosts

    - name: Remove old files on server
      run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_SSH_USERNAME }}@${{ secrets.SERVER_SSH_PAAS_IP }} \
            "rm -rf /var/www/html/geometry/"

    - name: upload files
      run: |
        scp -i ~/.ssh/id_rsa geometry.zip \
          ${{ secrets.SERVER_SSH_USERNAME }}@${{ secrets.SERVER_SSH_PAAS_IP }}:/var/www/html/

    - name: Unzip on server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_SSH_USERNAME }}@${{ secrets.SERVER_SSH_PAAS_IP }} \
          "unzip -o /var/www/html/geometry.zip -d /var/www/html/"